name: Build and deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '6.0.x'
  AZURE_WEBAPP_NAME: 'MyDotNetApp'
  AZURE_WEBAPP_PACKAGE_PATH: './published'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore MyDotNetApp.csproj
      
    - name: Build application
      run: dotnet build MyDotNetApp.csproj --configuration Release --no-restore
      
    - name: Run tests (if any)
      run: dotnet test MyDotNetApp.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
      
    - name: Publish application
      run: dotnet publish MyDotNetApp.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
